### ISSUE TITLE
Release 0.1.0 tracking issue

### ISSUE THREAD

**Issue by ubruhin** [LibrePCB/LibrePCB#340]
To keep track of the release 0.1.0.

## Before Release

- [x] Resolve [Prepare and test file format upgrade procedure](https://github.com/LibrePCB/LibrePCB/issues/185)
- [x] Merge [Doxygen: Add documentation about file format upgrade](https://github.com/LibrePCB/LibrePCB/issues/338)
- [x] Merge [Hide UUIDs in many windows and dialogs](https://github.com/LibrePCB/LibrePCB/issues/337)
- [x] Wait for feedback to [Any critical changes needed before the first release?](https://github.com/LibrePCB/LibrePCB/issues/339)
- [x] Add most important elements to [our libraries](https://github.com/LibrePCB-Libraries)
- [x] Check if [Milestone 0.1](https://github.com/LibrePCB/LibrePCB/milestone/1) is completed
- [x] [Prepare new download page for website](https://github.com/LibrePCB/LibrePCB.github.io/pull/20) (but not publishing yet)
- [x] [Prepare release blog post](https://github.com/LibrePCB/LibrePCB.github.io/pull/19) (but not publishing yet)

## Release

- [x] Follow [Release Checklist](https://developers.librepcb.org/da/dbc/doc_release_workflow.html#doc_release_workflow_checklist)
- [x] Update installers (add package "librepcb-stable" and remove "librepcb-nightly")

## After Release

- [x] Publish new download page of website by merging https://github.com/LibrePCB/LibrePCB.github.io/pull/20
- [x] Update installation instructions by merging https://github.com/LibrePCB/librepcb-doc/pull/23
- [x] Publish the already prepared blog post by merging https://github.com/LibrePCB/LibrePCB.github.io/pull/19
- [x] Remove all backward compatibility code on the `master` branch

## Add/Update Packages

- [x] Update [Gentoo package](https://packages.gentoo.org/packages/sci-electronics/librepcb) (fixes #283)
- [x] Update [NixOS Package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/science/electronics/librepcb/default.nix)
- [x] Update [OpenPandora Package](https://repo.openpandora.org/?page=detail&app=librepcb)
- [x] Add package to AUR (maybe remove [librepcb-git](https://aur.archlinux.org/packages/librepcb-git/))
- [x] Add package to [Flathub](https://flathub.org/home) (see https://github.com/LibrePCB/librepcb-rfcs/issues/26)
- [ ] ~Add package to [Homebrew](https://brew.sh/)~ Postponed for a future release.
- [ ] ~Add package to [Chocolatey](https://chocolatey.org/)~ Postponed for a future release.

**Comment by dbrgn** [comment]
I think we should have at least a set of basic library elements (e.g. pin headers and socket strips, a few resistors, a few capacitors, a few LEDs) ready when we release the first version. Otherwise, people trying out the software can't really do anything with it without creating new symbols and footprints, which requires some reading to understand the concepts.

**Comment by ubruhin** [comment]
ACK -> Added it to the ToDo list above.

**Comment by rnestler** [comment]
We should also prepare a release announcement blog-post where we explain the scope of the release (beta-test, file format upgrade ability guarantee, ...)

**Comment by rnestler** [comment]
> Remove all backward compatibility code on the master branch

Shoudl't this be done before the release?

**Comment by ubruhin** [comment]
> We should also prepare a release announcement blog-post where we explain the scope of the release

Added to the list.

> Shoudl't this be done before the release?

No, I want to have backward compatibility in the 0.1 release because every already existing project (with intermediate file format) should be usable with the first official release. This way everyone can smoothly switch from nightly builds to stable releases.

**Comment by ubruhin** [comment]
I cleaned up all our libraries and added some more important elements. In addition, @dbrgn will add many connector elements soon. Of course there are still many things missing, but it's not reasonable to delay the release just because there are missing library elements. So I'll mark the task "Add most important elements to our libraries" as completed.

**Comment by ubruhin** [comment]
Completed -> closing this issue.
