### ISSUE TITLE
CLI: Add more features needed for LibrePCB Fab

### ISSUE THREAD

**Issue by ubruhin** [LibrePCB/LibrePCB#999]
##### SUMMARY

Currently on fab.librepcb.org we do some things manually because the CLI doesn't support them. It would be much easier if the CLI has built-in support for that:

- [x] Generate pick&place files (at least Gerber X3) -> #1005
- [ ] Output various metadata about a project (e.g. as JSON):
  - File format
  - Filename of `*.lpp` when opened an `*.lppz` file
  - List of boards:
    - Board index 
    - Board name
    - Board path
    - Inner layer count
    - Board size (bounding box)
- [x] Removing boards from a project -> #1016
- [x] Specify boards by index instead of by name -> #1017
- [ ] Optional: Generating board previews with realistic colors

##### SOLUTION

tbd
